### ISSUE TITLE
Duplicate symbol errors when compiling atlas_buidler on macOS arm64

### ISSUE THREAD

**Issue by pauseState** [karl-zylinski/odin-raylib-hot-reload-game-template#18]
When building the latest version of the template on macOS arm64, I get a few errors compiling the `atlas_builder` due to duplicate symbols getting linked.

It looks to specifically be from both `stb/rect_pack` and raylib getting imported in `atlas_builder.odin`.

```
duplicate symbol '_stbrp_init_target' in:
    /<OBFUSCATED>/Odin/vendor/stb/lib/darwin/stb_rect_pack.a
    /<OBFUSCATED>/Odin/vendor/raylib/macos-arm64/libraylib.a[arm64][5](rtext.o)
duplicate symbol '_stbrp_pack_rects' in:
    /<OBFUSCATED>/Odin/vendor/stb/lib/darwin/stb_rect_pack.a
    /<OBFUSCATED>/Odin/vendor/raylib/macos-arm64/libraylib.a[arm64][5](rtext.o)
duplicate symbol '_stbrp_setup_allow_out_of_mem' in:
    /<OBFUSCATED>/Odin/vendor/stb/lib/darwin/stb_rect_pack.a
    /<OBFUSCATED>/Odin/vendor/raylib/macos-arm64/libraylib.a[arm64][5](rtext.o)
duplicate symbol '_stbrp_setup_heuristic' in:
    /<OBFUSCATED>/Odin/vendor/stb/lib/darwin/stb_rect_pack.a
    /<OBFUSCATED>/Odin/vendor/raylib/macos-arm64/libraylib.a[arm64][5](rtext.o)
ld: 4 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm still pretty new-ish to Odin, so I'm not 100% certain if this is a result of how Odin is choosing to import the respective libraries for these or a result of how this project runs a build for the `atlas_builder`.

**Comment by karl-zylinski** [comment]
Hi, this is a raylib issue. However, I think you can work around it by using the shared library version of raylib. Use `-define:RAYLIB_SHARED=true` when you compile the atlas_builder.

I will work on removing the raylib dependency from the atlas builder

**Comment by karl-zylinski** [comment]
https://github.com/karl-zylinski/atlas-builder no longer depends on raylib. It now uses a combination of stb libs and some homemade image blitting to generate the atlas. This should fix the raylib conflicts you saw.
